server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth-service

jwt:
  secret:
    key: bxcxvcvxNsapkdvopasjvdpsakvd7GNnbgdsfgV5Dfvdsavdasjzvcxvcx90kFDS
  expiration: 900